### ISSUE TITLE
Chaine non traduite : "Product is available again"

### ISSUE THREAD

**Issue by vz777** [thelia-modules/StockAlert#8]
Après plusieurs heures à chercher,
pour les deux mails, soit pour le retour en stock pour customer, soit pour le passage hors stock coté admin,
je ne sais pas pourquoi le sujet du mail n'est pas traduite.

J'ai chercher à modifier StockALert.php, ligne 86/87

                $message->setSubject(
                    $this->trans('Product TEST is available again', [], $locale)
                );

Non seulement le message arrive en anglais mais au lieu de m'afficher 
"Product TEST is available again"
ça m'affiche : 
"Product is available again"

Merci d'avance

**Comment by roadster31** [comment]
L'erreur est ici : 
```
            foreach ($languages as $language) {
                $locale = $language->getLocale();
                $message->setLocale($locale);
                $message->setTitle(
                    $this->trans('Stock Alert - Customer', [], $locale)
                );
                $message->setSubject(
                    $this->trans('Product {$product_title} is available again', [], $locale)
                );
            }
```
Ca ne marche pas comme ça :) Il faut remplacer tout le bloc par : 
```
             $message->setTitle(
                    $this->trans('Stock Alert - Customer', [], self::MESSAGE_DOMAIN)
                );
                $message->setSubject(
                    $this->trans('Product {$product_title} is available again', [], self::MESSAGE_DOMAIN)
                );
```

Ensuite aller dans Configuration -> Traductions -> Modules -> Stock Alert -> Core Files et traduire ces deux chaines.

**Comment by vz777** [comment]
Merci Roadster,
j'essaie vraiment de comprendre 
mais ça ne marche pas, peut être trop de "$message",




 if (null === MessageQuery::create()->findOneByName('stockalert_customer')) {

            $message = new Message();
            $message
                ->setName('stockalert_customer')
                ->setHtmlTemplateFileName('alert-customer.html')
                ->setHtmlLayoutFileName('')
                ->setTextTemplateFileName('alert-customer.txt')
                ->setTextLayoutFileName('')
                ->setSecured(0);


            $message->setTitle(
                    $this->trans('Stock Alert - Customer', [], self::MESSAGE_DOMAIN)
                );
                $message->setSubject(
                    $this->trans('Product {$product_title} is available again', [], self::MESSAGE_DOMAIN)
                );    

            $message->save();

            $message = new Message();
            $message
                ->setName('stockalert_administrator')
                ->setHtmlTemplateFileName('alert-administrator.html')
                ->setHtmlLayoutFileName('')
                ->setTextTemplateFileName('alert-administrator.txt')
                ->setTextLayoutFileName('')
                ->setSecured(0);

             $message->setTitle(
                    $this->trans('Stock Alert - Administrator', [], self::MESSAGE_DOMAIN)
                );
                $message->setSubject(
                    $this->trans('Product {$product_title} is nearly out of stock', [], self::MESSAGE_DOMAIN)
                );

            $message->save();
        }

**Comment by roadster31** [comment]
Je viens de commiter une nouvelle version du module qui devrait régler le problème :)

Peux-tu me le confirmer ?

**Comment by vz777** [comment]
Malgré ce magnifique commit,
et vidage cache,
le problème est toujours la.

Par contre le title du product est récupéré correctement maintenant donc ça c'est cool

**Comment by roadster31** [comment]
Quel problème est toujours là ?

**Comment by vz777** [comment]
Je t'ai forwardé sur ta boite mail le message.

Le sujet du mail est toujours en anglais

**Comment by roadster31** [comment]
Ha ok. Essaie de désactiver puis réactiver le module.
Si ça ne suffit pas, désactive le module, supprime à la main les messages, et reactive le module.

**Comment by vz777** [comment]
Qu'est ce que tu veux dire par : 
"supprime à la main les messages" ?

**Comment by roadster31** [comment]
Configuration-> templates email->suppriper les deux messages.
et ensuite reactiver le module pour recreer les messages.

**Comment by vz777** [comment]
youpi, merci Franck !

Je clos l'issue du coup.
